use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    // Only generate embed metadata when the feature is enabled.
    if env::var_os("CARGO_FEATURE_EMBED_MODELS").is_none() {
        return;
    }

    println!("cargo:rerun-if-env-changed=AIEGIS_EMBED_PACKAGES");

    let packages_raw =
        env::var("AIEGIS_EMBED_PACKAGES").unwrap_or_else(|_| "meta_prompt_guard_86m".to_string());
    let package_ids: Vec<String> = packages_raw
        .split(',')
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
        .map(|s| s.to_string())
        .collect();

    if package_ids.is_empty() {
        panic!("embed-models is enabled, but AIEGIS_EMBED_PACKAGES is empty");
    }

    for id in &package_ids {
        if !id.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
            panic!(
                "Invalid package id '{id}' in AIEGIS_EMBED_PACKAGES. Allowed: [A-Za-z0-9_]"
            );
        }
    }

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let generated_path = out_dir.join("aiegis_embedded_models.rs");

    let mut body = String::new();
    body.push_str("// @generated by build.rs\n");
    body.push_str("// This file is included by src/detection/embedded.rs when the embed-models feature is enabled.\n");
    body.push_str("pub const EMBEDDED_MODELS: &[super::EmbeddedModel] = &[\n");

    for id in &package_ids {
        let model_path = manifest_dir
            .join("models")
            .join("packages")
            .join(id)
            .join("model.onnx");
        let tokenizer_path = manifest_dir
            .join("models")
            .join("packages")
            .join(id)
            .join("tokenizer.json");

        println!("cargo:rerun-if-changed={}", model_path.display());
        println!("cargo:rerun-if-changed={}", tokenizer_path.display());

        if !model_path.exists() {
            panic!(
                "embed-models enabled, but ONNX model missing at {}. Populate models/packages/{id}/model.onnx before building (private flow: run aiegis-module-rs/scripts/quickstart_base_models.sh).",
                model_path.display()
            );
        }
        if !tokenizer_path.exists() {
            panic!(
                "embed-models enabled, but tokenizer missing at {}. Populate models/packages/{id}/tokenizer.json before building (private flow: run aiegis-module-rs/scripts/quickstart_base_models.sh).",
                tokenizer_path.display()
            );
        }

        // Keep paths anchored to CARGO_MANIFEST_DIR so builds don't depend on OUT_DIR layout.
        body.push_str(&format!(
            "    super::EmbeddedModel {{ package: \"{id}\", model: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/models/packages/{id}/model.onnx\")), tokenizer: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/models/packages/{id}/tokenizer.json\")) }},\n"
        ));
    }

    body.push_str("];\n");

    fs::write(&generated_path, body).expect("write embedded model metadata");
}

