use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    // Embedded ONNX model packages (`embed-models`).
    if env::var_os("CARGO_FEATURE_EMBED_MODELS").is_some() {
        println!("cargo:rerun-if-env-changed=AIEGIS_EMBED_PACKAGES");

        let packages_raw = env::var("AIEGIS_EMBED_PACKAGES")
            .unwrap_or_else(|_| "meta_prompt_guard_86m".to_string());
        let package_ids: Vec<String> = packages_raw
            .split(',')
            .map(|s| s.trim())
            .filter(|s| !s.is_empty())
            .map(|s| s.to_string())
            .collect();

        if package_ids.is_empty() {
            panic!("embed-models is enabled, but AIEGIS_EMBED_PACKAGES is empty");
        }

        for id in &package_ids {
            if !id.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
                panic!(
                    "Invalid package id '{id}' in AIEGIS_EMBED_PACKAGES. Allowed: [A-Za-z0-9_]"
                );
            }
        }

        let generated_path = out_dir.join("aiegis_embedded_models.rs");
        let mut body = String::new();
        body.push_str("// @generated by build.rs\n");
        body.push_str("// This file is included by src/detection/embedded.rs when the embed-models feature is enabled.\n");
        body.push_str("pub const EMBEDDED_MODELS: &[super::EmbeddedModel] = &[\n");

        for id in &package_ids {
            let model_path = manifest_dir
                .join("models")
                .join("packages")
                .join(id)
                .join("model.onnx");
            let tokenizer_path = manifest_dir
                .join("models")
                .join("packages")
                .join(id)
                .join("tokenizer.json");

            println!("cargo:rerun-if-changed={}", model_path.display());
            println!("cargo:rerun-if-changed={}", tokenizer_path.display());

            if !model_path.exists() {
                panic!(
                    "embed-models enabled, but ONNX model missing at {}. Populate models/packages/{id}/model.onnx before building (private flow: run aiegis-module-rs/scripts/quickstart_base_models.sh).",
                    model_path.display()
                );
            }
            if !tokenizer_path.exists() {
                panic!(
                    "embed-models enabled, but tokenizer missing at {}. Populate models/packages/{id}/tokenizer.json before building (private flow: run aiegis-module-rs/scripts/quickstart_base_models.sh).",
                    tokenizer_path.display()
                );
            }

            // Keep paths anchored to CARGO_MANIFEST_DIR so builds don't depend on OUT_DIR layout.
            body.push_str(&format!(
                "    super::EmbeddedModel {{ package: \"{id}\", model: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/models/packages/{id}/model.onnx\")), tokenizer: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/models/packages/{id}/tokenizer.json\")) }},\n"
            ));
        }

        body.push_str("];\n");
        fs::write(&generated_path, body).expect("write embedded model metadata");
    }

    // Embedded GGUF local LLM weights (`embed-llm-weights`).
    //
    // This builds a single-file binary that can run local inference without shipping
    // a separate `models/llm/*.gguf` directory. The GGUF is provided at build time
    // and copied into OUT_DIR so it can be included via include_bytes!.
    if env::var_os("CARGO_FEATURE_EMBED_LLM_WEIGHTS").is_some() {
        println!("cargo:rerun-if-env-changed=AIEGIS_EMBED_LLM_GGUF_PATH");

        let gguf_src = env::var("AIEGIS_EMBED_LLM_GGUF_PATH").unwrap_or_else(|_| {
            panic!("embed-llm-weights is enabled, but AIEGIS_EMBED_LLM_GGUF_PATH is not set")
        });
        let gguf_src_path = PathBuf::from(&gguf_src);
        if !gguf_src_path.exists() {
            panic!(
                "AIEGIS_EMBED_LLM_GGUF_PATH does not exist: {}",
                gguf_src_path.display()
            );
        }
        if gguf_src_path
            .extension()
            .and_then(|e| e.to_str())
            .unwrap_or("")
            != "gguf"
        {
            panic!(
                "AIEGIS_EMBED_LLM_GGUF_PATH must point to a .gguf file: {}",
                gguf_src_path.display()
            );
        }

        println!("cargo:rerun-if-changed={}", gguf_src_path.display());

        let gguf_dst_name = "aiegis_embedded_llm.gguf";
        let gguf_dst_path = out_dir.join(gguf_dst_name);
        fs::copy(&gguf_src_path, &gguf_dst_path).expect("copy GGUF into OUT_DIR");

        let len = fs::metadata(&gguf_dst_path)
            .expect("stat embedded GGUF")
            .len();
        let basename = gguf_src_path
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or("embedded.gguf");

        let generated_path = out_dir.join("aiegis_embedded_llm.rs");
        let body = format!(
            r#"// @generated by build.rs
// This file is included by src/detection/embedded_llm.rs when embed-llm-weights is enabled.
pub const EMBEDDED_LLM_GGUF_NAME: &str = {basename:?};
pub const EMBEDDED_LLM_GGUF_LEN: usize = {len}usize;
pub const EMBEDDED_LLM_GGUF_BYTES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/{gguf_dst_name}"));
"#
        );
        fs::write(&generated_path, body).expect("write embedded LLM metadata");
    }
}
